### PR TITLE
add makefile to uni operate.

### PR DESCRIPTION
**Pull request by tiannian**

### CODE REVIEW

**Review by malefooo — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]

**Comment by Baoyuantop** [comment]
bors merge

**Comment by tiannian** [comment]
ohhhh, I need modify bors.yml

**Comment by tiannian** [comment]
bors try

**Comment by tiannian** [comment]
bors try

**Comment by tiannian** [comment]
bors try

**Comment by tiannian** [comment]
bors try

**Comment by tiannian** [comment]
bors try

**Pull request merged**
