### PR TITLE
Dev add actor

### PR DESCRIPTION
**Pull request by tiannian**
add a macro to expose actor's abi to runtime.

### CODE REVIEW

**Comment by tiannian** [comment]
Current work for async function. refer to `examples/actor` sample project. @malefooo 
By default, json file generated under `target/abi`. @Baoyuantop

**Review by Baoyuantop — APPROVED** [review]

**Review by malefooo — APPROVED** [review]

**Comment by malefooo** [comment]
bros merge

**Comment by Baoyuantop** [comment]
bros merge

**Comment by Baoyuantop** [comment]
bors merge

**Comment by Baoyuantop** [comment]
bors merge

**Pull request merged**
